# Generated by Django 2.2.24 on 2021-09-30 17:45

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('cat', models.CharField(choices=[('home_join', 'Rejoignez nous'), ('home_contact', 'Nous Contacter'), ('home_rep', "Répertoire de l'acceuil"), ('login', 'Connexion'), ('change_membre', 'Modification du profil'), ('inscription_membre', 'Inscription'), ('home', 'Calendrier connecté'), ('liste', 'Agenda public'), ('part', 'Répertoire'), ('instru', 'Instruments'), ('n', "N'apparait pas")], default='n', max_length=127)),
                ('auteur', models.CharField(blank=True, max_length=127, null=True, verbose_name="Auteur de l'image")),
                ('url', models.URLField(blank=True, null=True, verbose_name="Lien vers le site de l'auteur")),
                ('color', colorful.fields.RGBColorField(default='#ffffff', verbose_name="Couleur du nom de l'auteur")),
                ('image', models.ImageField(default=None, upload_to='trombonoscope/deco', validators=[gestion.models.Photo.validate_image])),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('order', models.IntegerField(verbose_name='ordre')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='OssiaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ossia', models.BooleanField(default=True, verbose_name="Membre de l'Ossia")),
                ('is_chef', models.BooleanField(default=False, verbose_name='Chef Fanfare')),
                ('phone', models.CharField(blank=True, help_text='seulement visible par les chef·fe·s', max_length=20, verbose_name='Téléphone')),
                ('instru', models.CharField(choices=[('Clarinette', 'Clarinette'), ('Euphonium', 'Euphonium'), ('Percussion', 'Percussion'), ('Piccolo', 'Piccolo'), ('Saxophone Alto', 'Saxophone Alto'), ('Saxophone Ténor', 'Saxophone Ténor'), ('Saxophone Baryton', 'Saxophone Baryton'), ('Souba', 'Souba'), ('Trombone', 'Trombone'), ('Trompette', 'Trompette'), ('Autre', 'Autre'), ('ne sais pas', 'Je ne sais pas encore')], default='ne sais pas', max_length=40, verbose_name='Instrument joué')),
                ('instru_autre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lequel ?')),
                ('slug', models.CharField(editable=False, max_length=7, unique=False)),
                ('doodlename', models.CharField(blank=True, max_length=30, verbose_name='Nom pour le doodle')),
                ('trombonoscope', models.CharField(choices=[('non', 'Non'), ('o_a', 'Oui en tant que fanfaron actuel'), ('o_v', 'Oui en tant que vie·ille·ux')], default='non', max_length=3, null=True, verbose_name='Je souhaite apparaitre dans le trombonoscope:')),
                ('instru_trombonoscope', models.CharField(blank=True, max_length=30, verbose_name='Instrument affiché sur le trombonoscope')),
                ('nom_trombonoscope', models.CharField(blank=True, max_length=30, verbose_name='Nom affiché sur le trombonoscope')),
                ('trombonoscope_colors', models.CharField(choices=[('#e4522f#ffffff', 'Orange et Blanc'), ('#ffffff#000000', 'Blanc et Noir'), ('#A8107C#000000', 'Rose et Noir'), ('#10A4A8#ffffff', 'Bleu et Blanc'), ('#26A810#000000', 'Vert et Noir'), ('#A81026#ffffff', 'Rouge et Blanc'), ('#E3E54C#000000', 'Jaune et Noir'), ('autre', 'Autre')], default='OrangeBlanc', max_length=40, verbose_name='Couleur du profil')),
                ('trombonoscope_fond', colorful.fields.RGBColorField(default='#e4522f', verbose_name='Couleur de fond du profil')),
                ('trombonoscope_texte', colorful.fields.RGBColorField(default='#ffffff', verbose_name='Couleur du texte du profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Musicien',
                'verbose_name_plural': 'Profil Musicien',
            },
        ),
    ]
