# Generated by Django 4.2.13 on 2024-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_remove_ossiauser_instru_trombonoscope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ossiauser",
            name="slug",
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
