# Generated by Django 2.2.24 on 2021-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Info')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Info en anglais')),
                ('order', models.IntegerField(verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ('order',),
            },
        ),
    ]
