# Generated by Django 2.2.24 on 2021-09-30 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('order', models.IntegerField(verbose_name='ordre')),
                ('nom_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PartitionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('download_unlogged', models.CharField(choices=[('n', 'Non'), ('o', 'Oui')], default='n', max_length=1, verbose_name='Téléchargeable non connecté ?')),
                ('infos', models.TextField(blank=True, default='', verbose_name='Infos utiles')),
                ('infos_en', models.TextField(blank=True, default='', verbose_name='Infos utiles en anglais')),
                ('url', models.URLField(blank=True, help_text='Dans Youtube cliquer sur partager puis importer pour récuperer la bonne adresse', null=True, verbose_name="Url d'une video youtube")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partitions.Category', verbose_name='Type de partition')),
            ],
            options={
                'verbose_name': 'Morceau',
                'verbose_name_plural': 'Morceaux',
                'ordering': (django.db.models.functions.text.Lower('nom'),),
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('part', models.FileField(upload_to='partitions/')),
                ('morceau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partitions.PartitionSet')),
            ],
            options={
                'verbose_name': 'Morceau',
                'verbose_name_plural': 'Morceaux',
                'ordering': (django.db.models.functions.text.Lower('nom'),),
            },
        ),
    ]
