# Generated by Django 2.2.24 on 2021-11-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitionset',
            name='download_unlogged',
        ),
        migrations.RemoveField(
            model_name='partitionset',
            name='url',
        ),
    ]
