# Generated by Django 2.2.24 on 2021-09-30 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nomcourt', models.CharField(max_length=9, verbose_name='Nom court')),
                ('date', models.DateField()),
                ('debut', models.TimeField()),
                ('fin', models.TimeField(blank=True, null=True)),
                ('slug', models.CharField(default=uuid.uuid1, editable=False, max_length=7, unique=True)),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('desc_users', models.TextField(blank=True, null=True, verbose_name='Infos (visible seulement des fanfaron·ne·s)')),
                ('desc_users_en', models.TextField(blank=True, null=True, verbose_name='Infos en anglais (visible seulement des fanfaron·ne·s')),
                ('calendrier', models.CharField(choices=[('F', 'Visible seulement par les fanfarons'), ('T', 'Afficher dans le calendrier pour tous'), ('H', 'Hall of fame'), ('C', 'Visible seulement par les cheff·e·s'), ('D', "Visible seulement par les cheff·e·s et sur l'agenda public")], default='F', max_length=1)),
            ],
            options={
                'verbose_name': 'Evenement',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('pe', 'Peut-etre')], default='non', max_length=20, verbose_name='Réponse')),
                ('instrument', models.CharField(blank=True, max_length=50, null=True)),
                ('dont_play_main', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], default='Non', max_length=3, verbose_name="Je veux jouer d'un instrument different de mon instrument principal:")),
                ('details', models.CharField(blank=True, max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendrier.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.OssiaUser')),
            ],
        ),
    ]
