# Generated by Django 2.2.24 on 2021-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='dont_play_main',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='instrument',
        ),
        migrations.AlterField(
            model_name='event',
            name='calendrier',
            field=models.CharField(choices=[('F', 'Visible seulement par les muscisiens'), ('T', 'Afficher dans le calendrier pour tous'), ('H', 'Hall of fame'), ('C', 'Visible seulement par les cheff·e·s'), ('D', "Visible seulement par les cheff·e·s et sur l'agenda public")], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc_users',
            field=models.TextField(blank=True, null=True, verbose_name='Infos (visible seulement des muscisien·ne·s)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc_users_en',
            field=models.TextField(blank=True, null=True, verbose_name='Infos en anglais (visible seulement des muscisien·ne·s'),
        ),
    ]
