# Generated by Django 2.2.24 on 2021-10-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_auto_20211021_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='details',
        ),
    ]
